### ISSUE TITLE
problems with octave in linux

### ISSUE THREAD

**Issue by vinit-agr** [zk00006/OpenTLD#11]
have resolved quite a lot of problems, but got stuck here. Please help.

error: X and Y size must match Z dimensions
error: called from:
error:   /usr/share/octave/3.2.4/m/general/interp2.m at line 326, column 2
error:   /usr/share/octave/packages/3.2/image-1.0.12/imremap.m at line 106, column 8
error:   /usr/share/octave/packages/3.2/image-1.0.12/imremap.m at line 83, column 8
error:   /usr/share/octave/packages/3.2/image-1.0.12/imresize.m at line 101, column 7
error:   /home/vinit/Downloads/tld/zk00006-OpenTLD-4649a5d/tld/tldPatch2Pattern.m at line 20, column 9
error:   /home/vinit/Downloads/tld/zk00006-OpenTLD-4649a5d/tld/tldGetPattern.m at line 41, column 14
error:   /home/vinit/Downloads/tld/zk00006-OpenTLD-4649a5d/tld/tldGeneratePositiveData.m at line 45, column 5
error:   /home/vinit/Downloads/tld/zk00006-OpenTLD-4649a5d/tld/tldInit.m at line 82, column 15
error:   /home/vinit/Downloads/tld/zk00006-OpenTLD-4649a5d/tld/tldExample.m at line 35, column 5
error:   run_TLD.m at line 42, column 12

thanks 

--Vinit

**Comment by zk00006** [comment]
This message fitts better to OpenTLD discussion group!

**Comment by jkcunningham** [comment]
I am sorry to see this closed, as I arrived here trying to track down the same error message and I'm not using openTLD. I have a simple RGB image 240x320 pixels which imresize(I,0.5) won't work on. 

octave> I = imresize(I,.5);  
error: X and Y size must match Z dimensions
error: called from:
error:   /home/jcunningham/Desktop/snakes/code-examples/localized_seg/interp2.m at line 329, column 6
error:   /home/jcunningham/Desktop/snakes/code-examples/localized_seg/imremap.m at line 108, column 12
error:   /home/jcunningham/Desktop/snakes/code-examples/localized_seg/imremap.m at line 86, column 21
error:   /home/jcunningham/Desktop/snakes/code-examples/localized_seg/imresize.m at line 105, column 7
octave> 

The local copies that are referenced in the error message were copied directly from /usr/share/octave/3.2.4 tree so I could step through them more easily. Has anyone else experienced this problem?
