### ISSUE TITLE
Possible bug in fern.cpp

### ISSUE THREAD

**Issue by rayryeng** [zk00006/OpenTLD#13]
Hi all,

I think there is a possible bug in the fern.cpp code.  Under mex/fern.cpp, line 430, I believe the code should be:

double bboxvar = bbox_var_offset(IIMG,IIMG2,BBOX+(idx[j]-1)*BBOX_STEP);

The code in the current version is:

double bboxvar = bbox_var_offset(IIMG,IIMG2,BBOX+j*BBOX_STEP);

This means that no matter which bounding box locations that have been found with the least amount of overlap, we will only be using the first numIdx indexed locations in the BBOX array, and not the ones with the least amount of overlap.

Not sure where to post this, so I figured this was the best spot to do so.

Thanks,
- Ray.

**Comment by smtlad** [comment]
Yes. I agree with rayryeng.

BBOX+(idx[j]-1)*BBOX_STEP will get the right bounding box.

**Comment by rayryeng** [comment]
Awesome, that's what I thought.  I haven't changed the code and recompiled yet.... but I'm wondering if this would make a significant effect to the results, in comparison to what has already been published.  Has anyone tried?  If not, I'll most likely do it over the next few days, and see what the results look like on the already provided test image sequence.  Either way, awesome work!

**Comment by bilderbuchi** [comment]
shouldn't be too difficult, you already know what you want to do. fork the repository, create a new branch (name it testing-bb or whatever), change the code, commit it in that branch. Then you can test, and change stuff, but you can get back to the stable "master" code in a heartbeat. 
For some starter help on how to do all that, look at the github help section and/or see here https://groups.google.com/forum/#!searchin/opentld/github/opentld/erEM1ee_lmY/OyzuJqvfw10J

**Comment by rayryeng** [comment]
Closing this. Old AF
