### ISSUE TITLE
How to track movie in RGB mode

### ISSUE THREAD

**Issue by shahabhameed** [zk00006/OpenTLD#25]
At present when I load a movie from a file , it tracks it in grayscale mode. Does anyone know how to track it in RGB or color mode. 

Thanks 

Regards,
Shahab Hameed

**Comment by TheMrtN** [comment]
This question could be a nice discussion in the Google Group. In fact, there has been discussions about this already. This Issues page is ment for issues (bugs or related problems) with the code.

**Comment by shahabhameed** [comment]
I have requested to join OpenTLD group , but I my membership is pending for 3 days. Please accept it as soon as possible. "shahabhameed@gmail.com"

**Comment by bilderbuchi** [comment]
maybe you have to contact zdenek directly (he's the admin of the group), per email (in his github profile). he's not really active in the google group anymore.
