### ISSUE TITLE
Tracking is very slow (about 6-9 fps)

### ISSUE THREAD

**Issue by shahabhameed** [zk00006/OpenTLD#26]
I was tracking an object in the movie but the tracking is too slow, approximately 6-9 fps. I was wondering if anyone know how to track accurately in real-time i.e. approximately 20-25 fps. 
Any pointers would be much appreciated. Thanks

**Comment by TheMrtN** [comment]
See OpenTLD's Google Group for pointers how to improve performance.

**Comment by shahabhameed** [comment]
My membership in the group is pending .. please accept it as soon as possible ... shahabhameed@gmail.com

**Comment by ArtyZe** [comment]
> My membership in the group is pending .. please accept it as soon as possible ... [shahabhameed@gmail.com](mailto:shahabhameed@gmail.com)

hello， have you solved this problem? My apply is also pending...
