### ISSUE TITLE
error: (-27) in Matlb 2012b with OpenCV2.4.2 in Windows 7

### ISSUE THREAD

**Issue by 8mike** [zk00006/OpenTLD#34]
I am getting this error when i try to execute run_TLD.m (compilation went fine)

Unexpected Standard exception from MEX file.
What() is:......\modules\core\src\matrix.cpp:1467: error: (-27) create() called for the missing
output array

..

Error in tldTracking (line 30)
xFJ    = lk(2,tld.img{I}.input,tld.img{J}.input,xFI,xFI); % track all points by Lucas-Kanade tracker
from frame I to frame J, estimate Forward-Backward error, and NCC for each point

Error in tldProcessFrame (line 25)
[tBB tConf tValid tld] = tldTracking(tld,tld.bb(:,I-1),I-1,I); % frame-to-frame tracking (MedianFlow)

Error in tldExample (line 41)
    tld = tldProcessFrame(tld,i); % process frame i

Error in run_TLD (line 42)
[bb,conf] = tldExample(opt);

**Comment by harguess** [comment]
8mike:  I'm getting the same exact issue.  How did you resolve this?

**Comment by harguess** [comment]
Never mind.  The suggestion here did the trick:
https://github.com/zk00006/OpenTLD/issues/22
