### ISSUE TITLE
Software versions in README

### ISSUE THREAD

**Issue by bilderbuchi** [zk00006/OpenTLD#4]
Please add information about which software package versions  were used/are minimum requirement for this code. This would save much effort with hunting down mysterious problems. 
For example, for using ~ as a placeholder for unused functions, MATLAB >=R2009b is necessary.

Thanks,
christoph

**Comment by zk00006** [comment]
Will do that. Thanks for feedback.
Zdenek

**Comment by bilderbuchi** [comment]
Clarification please: Is it necessary to use OpenCV Version 2.2 for some feature, or did you just install the latest, and would 2.1 be sufficient? 
Reason I ask is because at least on many linux distros (e.g Ubuntu), there is no packaged version of 2.2 available yet, and having to build it manually could be difficult. At least, I didn't succeed in building it on my 64bit system yesterday.
As far as I can see from comparing the different branches on here, some library names and paths have changed.
